### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MilanSavaliya321** [codecat15/HttpUtility#11]
![Screenshot 2021-08-23 at 11 07 58 AM](https://user-images.githubusercontent.com/38990640/130396155-d90ec390-f5a8-48c1-ba37-1f79bec4a5dd.png)

**Comment by codecat15** [comment]
did you import the utility? If yes then can you please provide a sample code for the same

**Comment by milangit03** [comment]
**Pod file + ViewController**

![Screenshot 2021-08-26 at 2 41 05 PM](https://user-images.githubusercontent.com/38990640/130935841-a71a8057-5dbb-49ff-98eb-e49bb01e7db1.png)

**Comment by prosenjitBeas** [comment]
Any solution?

**Comment by milangit03** [comment]
Simply drag below file from the pod to the main target project and use it.

https://github.com/codecat15/HttpUtility/tree/master/HttpUtility

**Comment by codecat15** [comment]
@Milan-Savaliya  Thank you for reporting this, the issue has been resolved in the latest release for the utility 1.2.2, please update your project pod using the command `pod update` to fetch the latest updates. Do close the issue once you have tested and are satisfied with the results and if not please add your comments here.

**Comment by codecat15** [comment]
closing this task, if the issue is still present please re-open it
