### ISSUE TITLE
How to return result or response to calling functinon?

### ISSUE THREAD

**Issue by chinmay-inaza** [codecat15/HttpUtility#24]
I want to return the response from API to where it is called from. like this: 

```
case .success(let driver):
                
            // code to handle the response
//                print("DRIVER: \(String(describing: driver))")
               
                return driver
```

How can I do such return?

Or any other work around?

I need to have all data in `driver` when I do:

driver = Driver().getDriver(id)

How to return from success closure?

**Comment by codecat15** [comment]
you can use escaping closures to return the response, checkout this video for the same
https://youtu.be/IIFWcBEWYK4
